name: Harvest setlist.fm
on:
  schedule:
    - cron: "0 3 1 * *" # 03:00 UTC on the 1st of each month
  workflow_dispatch: {}
jobs:
  harvest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run harvest:setlists
        env:
          SETLISTFM_API_KEY: ${{ secrets.SETLISTFM_API_KEY }}
      - name: Commit & push data
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add _data/
          git commit -m "chore(data): monthly setlist.fm harvest" || echo "No changes"
          git push